#!/bin/bash
#
#

FUSEKI_HOME=/root/data.sgul.ac.uk-deploy/data.sgul.ac.uk/resources/fuseki

fuseki_pid() {
  echo `ps aux | grep fuseki | grep -v "/etc/init.d/fuseki" | grep -v grep | awk '{ print $2 }'`
}

start() {
  pid=$(fuseki_pid)
  if [ -n "$pid" ]
  then
    echo "Fuseki is already running (pid: $pid)"
  else
    echo "Starting fuseki"
    $FUSEKI_HOME/fuseki-server --config=$FUSEKI_HOME/config-sgul.ttl &
    sleep 10
  fi


return 0
}

stop() {
  pid=$(fuseki_pid)
  if [ -n "$pid" ]
  then
    echo "Stopping Fuseki"
    kill -9 $pid

  fi
  return 0
}

case $1 in
start)
  start
;;
stop)
  stop
;;
restart)
  stop
  start
;;
status)
  pid=$(fuseki_pid)

  if [ -n "$pid" ]
  then
    echo "Fuseki is running with pid: $pid"
  else
    echo "Fuseki is not running"
  fi
;;
esac
exit 0

